### ISSUE TITLE
Not work in game

### ISSUE THREAD

**Issue by khoimeot** [tribalfs/Pixels#3]
I have changed the resolution on my sam phone and it appeared work well in the main menu , but when i tried to enter the game , the sceen come back to full hd+ which made my phone so hot and laggy , but when i quit the game , it is hd+ ( as i set in the app) any help ?

**Comment by Pokzaa1** [comment]
https://github.com/tribalfs/Pixels/blob/main/README.md

**Comment by Snddjsjxndnkakz** [comment]
نعم
