### ISSUE TITLE
Screen aspect ratio change?

### ISSUE THREAD

**Issue by KiKiHUN1** [tribalfs/Pixels#38]
Is there any way to change the aspect ratio of the screen?
Or stretch the resolution?

I have a note10 plus with aftermarket screen. It reports back as an original display resolution, but in real life the edge screen is cut down. So the icons are a bit stretched vertically.

If i set the custom resolution lower, the gpu will render black bars for the lost pixels, not stretch.

But if i set the built-in resolutions, the image will stretch, but again, wrong aspect ratio.

**Comment by tribalfs** [comment]
This is not possible.  Based on your description, this is not an issue of the aspect ratio but the size of the pixel itself.
