### ISSUE TITLE
Any way i can revert resolution?

### ISSUE THREAD

**Issue by dull-4h4n** [tribalfs/Pixels#4]
I accidentally lowered the resolution so low that i cannot revert it back because the ui got so small i cannot see the apps anymore.

Is there anyway i can revert it or do i have to externally factory reset my phone?

I also do not have usb debugging on anymore.
Thank you for any feedback.

**Comment by tribalfs** [comment]
Seems factory reset is the option left for your case.

**Comment by dull-4h4n** [comment]
Resetting work. Finding out how to open recovery mode was kind of a pain.
Thank you for the reply.
