### ISSUE TITLE
A "better" ADB tutorial

### ISSUE THREAD

**Issue by Rudxain** [tribalfs/Pixels#7]
There's already an official [tutorial here](https://developer.android.com/studio/debug/dev-options#enable). And [ADB can also be connected via WiFi](https://developer.android.com/studio/command-line/adb#connect-to-a-device-over-wi-fi), no need for USB. But Android Studio is unnecessary, I granted permissions to this app, by using /Llamalab/Automate's built-in ADB server, (only needs a pairing PIN). AM ADB can also "self connect", so there's no need for a secondary device!

**Comment by tribalfs** [comment]
Yes, I know.  I just want to put a simplest tutorial that is friendly to ADB newbies.
